version: "3.8"

services:
  frontend:
    container_name: frontend
    ports:
      - "8080:80"
    build:
      context: ./Calendar.UI
      dockerfile: ui.dockerfile

  # server-csharp:
  #   container_name: server-csharp
  #   ports:
  #     - "5003:5003"
  #   build:
  #     context: ./Calendar.CSharp
  #     dockerfile: server.dockerfile
  #   env_file:
  #     - .env.local
  server-java:
    container_name: server-java
    ports:
      - "5003:5003"
    build:
      context: ./Calendar.Java
      dockerfile: server.dockerfile
    env_file:
      - .env.local
